# version: "3.7"

# services:
#   app:
#     build: .
#     ports:
#       - "80:8081"
#     depends_on:
#       - db
#     environment:
#       SPRING_DATASOURCE_URL: jdbc:mysql://dineshdb.cb2m6c8i2qpk.eu-north-1.rds.amazonaws.com:3306/studentdb
#       SPRING_DATASOURCE_USERNAME: root
#       SPRING_DATASOURCE_PASSWORD: dinesh12
#       SPRING_JPA_HIBERNATE_DDL_AUTO: update
#     networks:
#       - app-network

#   db:
#     image: mysql:8.0
#     container_name: mysql-container
#     ports:
#       - "3307:3306"
#     environment:
#       MYSQL_ROOT_PASSWORD: password
#       MYSQL_DATABASE: studentdb
#       MYSQL_USER: user
#       MYSQL_PASSWORD: password
#     volumes:
#       - mysql-data:/var/lib/mysql
#     networks:
#       - app-network

# volumes:
#   mysql-data:

# networks:
#   app-network:
#     driver: bridge


version: "3.7"

services:
  app:
    build: .
    ports:
      - "80:8081"  
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://dineshdb.cb2m6c8i2qpk.eu-north-1.rds.amazonaws.com:3306/studentdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: dinesh12
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
